MovieTheaterTicketBookingSystem/Controllers/BookingController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MovieTheaterTicketBookingSystem.Helpers;
using MovieTheaterTicketBookingSystem.Models;
using Microsoft.Extensions.Hosting;

namespace MovieTheaterTicketBookingSystem.Controllers
{
    public class BookingController : Controller
    {
        private readonly string _filePath;

        public BookingController(IWebHostEnvironment env)
        {
            _filePath = System.IO.Path.Combine(env.ContentRootPath, "Content", "bookings.json");
        }

        public ActionResult Index()
        {
            var bookings = JsonFileHandler<Booking>.LoadFromFile(_filePath);
            return View(bookings);
        }

        public ActionResult Create(int showtimeID, int movieID)
        {
            ViewBag.ShowtimeID = showtimeID;
            ViewBag.MovieID = movieID;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Booking booking)
        {
            var bookings = JsonFileHandler<Booking>.LoadFromFile(_filePath);
            booking.BookingID = bookings.Count + 1;
            bookings.Add(booking);
            JsonFileHandler<Booking>.SaveToFile(_filePath, bookings);
            return RedirectToAction("Index");
        }
    }
}

MovieTheaterTicketBookingSystem/Controllers/MovieController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MovieTheaterTicketBookingSystem.Helpers;
using MovieTheaterTicketBookingSystem.Models;
using Microsoft.Extensions.Hosting;

namespace MovieTheaterTicketBookingSystem.Controllers
{
    public class MovieController : Controller
    {
        private readonly string _filePath;

        public MovieController(IWebHostEnvironment env)
        {
            _filePath = System.IO.Path.Combine(env.ContentRootPath, "Content", "movies.json");
        }

        public IActionResult Index()
        {
            var movies = JsonFileHandler<Movie>.LoadFromFile(_filePath);
            return View(movies);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            var movies = JsonFileHandler<Movie>.LoadFromFile(_filePath);
            movie.ID = movies.Count + 1;
            movies.Add(movie);
            JsonFileHandler<Movie>.SaveToFile(_filePath, movies);
            return RedirectToAction("Index");
        }

        public IActionResult Get(int id)
        {
            var movies = JsonFileHandler<Movie>.LoadFromFile(_filePath);
            var movie = movies.Find(m => m.ID == id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            var movies = JsonFileHandler<Movie>.LoadFromFile(_filePath);
            var index = movies.FindIndex(m => m.ID == movie.ID);
            if (index != -1)
            {
                movies[index] = movie;
                JsonFileHandler<Movie>.SaveToFile(_filePath, movies);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var movies = JsonFileHandler<Movie>.LoadFromFile(_filePath);
            var movie = movies.Find(m => m.ID == id);
            if (movie != null)
            {
                movies.Remove(movie);
                JsonFileHandler<Movie>.SaveToFile(_filePath, movies);
            }
            return RedirectToAction("Index");
        }
    }
}

MovieTheaterTicketBookingSystem/Controllers/ShowTimeController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MovieTheaterTicketBookingSystem.Helpers;
using MovieTheaterTicketBookingSystem.Models;
using Microsoft.Extensions.Hosting;

namespace MovieTheaterTicketBookingSystem.Controllers
{
    public class ShowtimeController : Controller
    {
        private readonly string _showtimesFilePath;
        private readonly string _moviesFilePath;

        public ShowtimeController(IWebHostEnvironment env)
        {
            _showtimesFilePath = System.IO.Path.Combine(env.ContentRootPath, "Content", "showtimes.json");
            _moviesFilePath = System.IO.Path.Combine(env.ContentRootPath, "Content", "movies.json");
        }

        public ActionResult Index()
        {
            var showtimes = JsonFileHandler<Showtime>.LoadFromFile(_showtimesFilePath);
            return View(showtimes);
        }

        public ActionResult Create()
        {
            var movies = JsonFileHandler<Movie>.LoadFromFile(_moviesFilePath);
            ViewBag.Movies = movies; // Pass the list of movies to the view
            return View();
        }

        [HttpPost]
        public ActionResult Create(Showtime showtime)
        {
            var showtimes = JsonFileHandler<Showtime>.LoadFromFile(_showtimesFilePath);
            showtime.ID = showtimes.Count + 1;
            showtimes.Add(showtime);
            JsonFileHandler<Showtime>.SaveToFile(_showtimesFilePath, showtimes);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var showtimes = JsonFileHandler<Showtime>.LoadFromFile(_showtimesFilePath);
            var showtime = showtimes.Find(s => s.ID == id);
            var movies = JsonFileHandler<Movie>.LoadFromFile(_moviesFilePath);
            ViewBag.Movies = movies; // Pass the list of movies to the view
            return View(showtime);
        }

        [HttpPost]
        public ActionResult Edit(Showtime showtime)
        {
            var showtimes = JsonFileHandler<Showtime>.LoadFromFile(_showtimesFilePath);
            var index = showtimes.FindIndex(s => s.ID == showtime.ID);
            if (index != -1)
            {
                showtimes[index] = showtime;
                JsonFileHandler<Showtime>.SaveToFile(_showtimesFilePath, showtimes);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var showtimes = JsonFileHandler<Showtime>.LoadFromFile(_showtimesFilePath);
            var showtime = showtimes.Find(s => s.ID == id);
            if (showtime != null)
            {
                showtimes.Remove(showtime);
                JsonFileHandler<Showtime>.SaveToFile(_showtimesFilePath, showtimes);
            }
            return RedirectToAction("Index");
        }
    }
}

MovieTheaterTicketBookingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>@ViewData["Title"] - MovieTheaterTicketBookingSystem</title>

    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- Bootstrap and Now UI Dashboard CSS -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/now-ui-dashboard.css" rel="stylesheet" />
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-color="orange">
            <div class="logo">
                <a href="/" class="simple-text logo-mini">MT</a>
                <a href="/" class="simple-text logo-normal">Movie Theater</a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="active">
                        <a href="@Url.Action("Index", "Home")">
                            <i class="now-ui-icons design_app"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Movie")">
                            <i class="now-ui-icons education_paper"></i>
                            <p>Movies</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Showtime")">
                            <i class="now-ui-icons ui-1_calendar-60"></i>
                            <p>Showtimes</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Booking")">
                            <i class="now-ui-icons business_money-coins"></i>
                            <p>Bookings</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Privacy", "Home")">
                            <i class="now-ui-icons users_single-02"></i>
                            <p>Privacy</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent bg-primary navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" href="#">@ViewData["Title"]</a>
                    </div>
                    <!-- Other navbar elements -->
                </div>
            </nav>
            <!-- End Navbar -->

            <div class="content" style="padding-top: 70px;">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>

            <footer class="footer" style="margin-top: 100px;">
                <div class="container-fluid">
                    <nav>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Licenses</a></li>
                        </ul>
                    </nav>
                    <div class="copyright">
                        &copy; 2024, made with <i class="fa fa-heart heart"></i> by Movie Theater
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <!-- Scripts -->
    <script src="~/assets/js/core/jquery.min.js"></script>
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/assets/js/now-ui-dashboard.js"></script>
</body>
</html>